name: Worker CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm --filter @vidforge/worker build
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Configure Docker to use gcr.io registry
      run: gcloud auth configure-docker gcr.io --quiet
    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/vidforge-worker:$GITHUB_SHA
        docker build -t $IMAGE_NAME ./apps/worker
        docker push $IMAGE_NAME
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy vidforge-worker \
          --image=$IMAGE_NAME \
          --platform=managed \
          --region=${{ secrets.GCP_REGION || 'us-central1' }} \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --allow-unauthenticated \
          --set-env-vars FFMPEG_PATH=${{ secrets.FFMPEG_PATH }}
